UMC-7-FIT-PASS/Fitpass-server

src/main/java/com/example/fitpassserver/domain/CoinPaymentHistory/entity/CoinPaymentHistory.java
src/main/java/com/example/fitpassserver/domain/coin/entity/Coin.java
src/main/java/com/example/fitpassserver/domain/coin/entity/CoinUsageHistory.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/Category.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/Status.java
src/main/java/com/example/fitpassserver/domain/fitnessPaymentHistory/entity/FitnessPaymentHistory.java
src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
src/main/java/com/example/fitpassserver/domain/member/entity/Role.java
src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
src/main/java/com/example/fitpassserver/domain/plan/entity/PlanName.java
src/main/java/com/example/fitpassserver/domain/review/entity/Review.java

Close #4
- 각 도메인 별 entity 작성
c32a09a3c89b8ed609c551379a785fc7bb082146
* 각 도메인 별 entity 작성
081ef572522f32d3871dae8b0293d2826693cf00
* @Builder.Defult 추가
b10bde7c0b74c94107e15a1a01c410bd88693c39
* @Setter 제거

:sparkles: feat(entity): 도메인 별 entity 작성

---

src/main/java/com/example/fitpassserver/domain/fitness/entity/exception/FitnessErrorCode.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/exception/FitnessException.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/review/controller/ReviewController.java
src/main/java/com/example/fitpassserver/domain/review/converter/ReviewConverter.java
src/main/java/com/example/fitpassserver/domain/review/dto/request/ReviewReqDTO.java
src/main/java/com/example/fitpassserver/domain/review/dto/response/ReviewResDTO.java
src/main/java/com/example/fitpassserver/domain/review/entity/Review.java
src/main/java/com/example/fitpassserver/domain/review/exception/ReviewErrorCode.java
src/main/java/com/example/fitpassserver/domain/review/exception/ReviewException.java
src/main/java/com/example/fitpassserver/domain/review/repsotiory/ReviewRepository.java
src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java

Close #7 
- 리뷰 관련 CRUD
0e4cc217ac39361321da4f86edeb5d4a07223d4c
fcd782877b642427bfb2e56253e75a0857d8d4c7
- 스웨거 및 인가는 유저 부분 완성되고 추가하겠습니다.
-

✨ [Feat] 리뷰 관련 기능

---

src/main/java/com/example/fitpassserver/domain/member/annotation/CurrentMember.java
src/main/java/com/example/fitpassserver/domain/member/annotation/resolver/CurrentMemberResolver.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
src/main/java/com/example/fitpassserver/global/config/WebConfig.java
src/main/java/com/example/fitpassserver/global/jwt/util/JwtProvider.java

Close #
- 일반 유저 관련 수정 
c3e29da8bc5b93344597b341681b20c222a6bf40
* plan entity 수정
ad7dd7b119bba46f24d1cdb4fe6718bde38df276
* @CurrentMemberResolver 등록
b1b126deb9ed3ade06bc98afd092b09bcf36ab6c
* 사용 x dto 주석 처리
ffdeb2b1dfce2b6d7392cc4f7ded0538a5c58bcb
*loginId로 변경

♻️ [Refactor] 일반 유저 기능 

---

src/main/java/com/example/fitpassserver/domain/fitness/controller/MemberFitnessController.java
src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessException.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java

Close #12 
- 보유 패스 조회, 사용하기
2cd655895052f9b1f8333792dcad732ee8af5149

✨ [Feat] 패스 조회, 사용하기

---

build.gradle
src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
src/main/java/com/example/fitpassserver/domain/member/entity/Role.java
src/main/java/com/example/fitpassserver/domain/member/principal/CustomOAuth2User.java
src/main/java/com/example/fitpassserver/domain/member/principal/CustomOAuth2UserService.java
src/main/java/com/example/fitpassserver/domain/member/repository/MemberRepository.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
src/main/java/com/example/fitpassserver/global/jwt/filter/JwtFilter.java
src/main/java/com/example/fitpassserver/global/oauth/OAuthAttributes.java
src/main/java/com/example/fitpassserver/global/oauth/handler/CustomOAuth2SuccessHandler.java
src/main/java/com/example/fitpassserver/global/oauth/provider/GoogleOAuth2UserInfo.java
src/main/java/com/example/fitpassserver/global/oauth/provider/NaverOAuth2UserInfo.java
src/main/java/com/example/fitpassserver/global/oauth/provider/OAuth2UserInfo.java

Close #16 
- OAuth 2.0을 이용한 소셜 로그인 기능(구글, 네이버)
50935625515aebe768892d871d33c76a1a6abbb8
- OAuth 2.0 설정 및 구글 소셜 로그인
aa13450a351ecef336bd2a0ce7ea28d86e4ed15b
- 네이버 소셜 로그인
e91efdc1905534d68303016799f3dce839d8eaa5
- 쿠키 만료시간 수정

✨ [Feat] 소셜 로그인 기능

---

src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/CursorPaginationResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessDetailResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessListResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessRecommendResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessSearchResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessListService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessRecommendService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessSearchService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
src/main/java/com/example/fitpassserver/domain/fitness/util/DistanceCalculator.java

Close #
- 임포트 부분 파일 경로 수정 대문자 -> 소문자
00b583ef9c7f3d0960daf629d2f875b7bb65d9e4

:memo: [Refactor] import 폴더 네임 수정

---

src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java

Close #26
- 사용자 현재 위치 설정
39a242766e22d2637f05f91041192c77dab16c0e

✨ [Feat] 사용자 현재 위치 설정

---

build.gradle
src/main/java/com/example/fitpassserver/domain/plan/repository/PlanRepository.java
src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileRequestDTO.java
src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileResponseDTO.java
src/main/java/com/example/fitpassserver/domain/profile/entity/Profile.java
src/main/java/com/example/fitpassserver/domain/profile/exception/ProfileErrorCode.java
src/main/java/com/example/fitpassserver/domain/profile/exception/ProfileException.java
src/main/java/com/example/fitpassserver/domain/profile/repositroy/ProfileRepository.java
src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java
src/main/java/com/example/fitpassserver/global/aws/s3/controller/S3Controller.java
src/main/java/com/example/fitpassserver/global/aws/s3/dto/S3UrlResponseDTO.java
src/main/java/com/example/fitpassserver/global/aws/s3/exception/S3ErrorCode.java
src/main/java/com/example/fitpassserver/global/aws/s3/exception/S3Exception.java
src/main/java/com/example/fitpassserver/global/aws/s3/service/S3Service.java
src/main/java/com/example/fitpassserver/global/aws/s3/util/S3Uploader.java
src/main/java/com/example/fitpassserver/global/config/S3Config.java

Close #23
- 프로필이미지 구현
7e423d000452cc7149bd55e5d5eaf932d1391307
회원가입시 바로 프로필이미지 생성하도록 리팩토링 예정

:sparkles: [Feat] 프로필 이미지 구현

---

src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
src/main/java/com/example/fitpassserver/domain/review/controller/ReviewController.java
src/main/java/com/example/fitpassserver/domain/review/converter/ReviewConverter.java
src/main/java/com/example/fitpassserver/domain/review/dto/response/ReviewResDTO.java
src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java

Close #40 
- 리뷰 조회 시 본인 리뷰 확인 isOwner 추가
795f6591069b26d7d9f5a647fcfe779b8ea70294

♻️ [Refactor] 리뷰 조회 시 본인 리뷰 확인

---

src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileResponseDTO.java
src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java

Close #46
- 프로필이미지 변수 타입 불일치 해결 
32dd5f28c53671e71d7483e6b701b02fd1c68850

:bug: [Bug] 프로필이미지 변수 불일치 해결

---

src/main/java/com/example/fitpassserver/domain/notice/controller/NoticeController.java
src/main/java/com/example/fitpassserver/domain/notice/controller/response/NoticeDetailResponse.java
src/main/java/com/example/fitpassserver/domain/notice/controller/response/NoticeListResponse.java
src/main/java/com/example/fitpassserver/domain/notice/exception/NoticeErrorCode.java
src/main/java/com/example/fitpassserver/domain/notice/exception/NoticeException.java
src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java

Close #
- 공지사항 상세조회, 목록 조회 api
admin나온 페이지에 카테고리에 관한 부분 없어서 일단 구현 안함

✨ [Feat] 공지사항 관련 기능

---

src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessSearchService.java
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

-179f650694343cc987730f0c0d6b872262cdc224
커스텀 에러로 수정
-652225e1097e4c074dd623615d28c1bb5b7f0ba7
로그인 안했을 때랑 설정 안했을 떄 서울 시청으로 두고 값 있을 땐 테이블에서 들고오게 수정
-eba7162d41840ab9596fb0687315cfbcdef73ae3
시큐리티 허용 url 추가 및 /search 부분 무한 스크롤 (거리순)

fitness 위도/경도 값 수정

---

src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java

:recycle: [Refactor] 회원탈퇴 url 변경

---

src/main/java/com/example/fitpassserver/domain/member/entity/Member.java

:recycle: [Refactor} status에 @Builder.Default 추가

---

src/main/java/com/example/fitpassserver/FitpassServerApplication.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/util/PassStatusScheduler.java

Close #57 
- 패스 상태 PROGRESS -> DONE 로직이 스케쥴러로 구현. ActiveTime이 1시간이 넘은 패스에 대하여 적용
9150f8732a257ee80ad0507b72eb1df725dc119e

♻️ refactor(memberfitness) 패스 상태 DONE 스케쥴러

---

src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java

:recycle: [Refactor] 유효성 검사 추가

---

src/main/java/com/example/fitpassserver/domain/coin/exception/CoinErrorCode.java
src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/CoinPaymentHistoryResponseListDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/entity/CoinPaymentHistory.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java

Close #48 
- 결제 내역 조회 API 구현
a4ebe8eefb11cffbe4a4f6029cbe52eb4b51bcca
- 결제 내역 조회 API  구현
31df214b1f4219d0491766c0edd59208fce4d363
- 패스 활성화 기간 수정

✨ [Feat] 결제 내역 조회 API 구현

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/CoinSinglePayRequestDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java

:recycle: [Refactor] 카카오페이 리팩토링

---

src/main/java/com/example/fitpassserver/domain/member/sms/controller/SmsController.java

Close #75
- https 적용 임의 컨트롤러 추가

:sparkles: [Feat} https 적용 임의 컨트롤러 추가

---

src/main/java/com/example/fitpassserver/global/oauth/handler/CustomOAuth2SuccessHandler.java

Close #68 
- OAuth 토큰 발급 방식 헤더로 변경
c12410924ada2188895b6e75e4e9f5309d558822
- OAuth 토큰 발급 방식 헤더로 변경

♻️ [Refactor] OAuth 토큰 발급 방식 헤더로 변경

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
src/main/java/com/example/fitpassserver/domain/member/sms/util/SmsCertificationUtil.java

Close #79
- 플랜 정기 결제 시 금액 부족 문자 발송
616f6557c82182bc7ff5e7584079d1da466e56fe

✨feat(plan) 금액 부족 시 문자 발송

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PlanSubScriptionRequestDTO.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java

Close #
- 
[659c1a0](https://github.com/UMC-7-FIT-PASS/Fitpass-server/pull/83/commits/659c1a0cb70cfbb4ad48c484b0c2d99bcac8c1ad) 정기 결제 수정

:recycle: [Refactor] : 플랜 정기 결제 카카오페이 로직 리팩토링

---

src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

:recycle: refactor(SecurityConfig): URL 수정

---

src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

:recycle: [Refactor]: patch 메소드 등록

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java

:bug: bug(KakaoPayService): kakao pay 변수 수정

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/CoinPaymentHistoryResponseListDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java

Close #88 
- 결제 내역 응답 필드 수정
80516e000f4a6a99bc1cc71693f8f67ae0567839
- 결제 내역 응답 필드 수정

🐛 [Fix] 결제 내역 응답 필드 수정

---

src/main/java/com/example/fitpassserver/global/jwt/util/JwtProvider.java

:bug: bug(JwtProvider): 시간 로그 추가

---

src/main/java/com/example/fitpassserver/global/jwt/util/JwtProvider.java

:recycle: refactor(JwtProvider): 토큰 시간 로그

---

src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileResponseDTO.java
src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java

Close https://github.com/UMC-7-FIT-PASS/Fitpass-server/issues/96
-

✨ [Feat]: profile에 coin 갯수 추가

---

src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessPaymentResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessPaymentService.java

Close #99 
- 피트니스 패스 구매 페이지 API 구현
b4fd1df6bf436ba3bd6668408a587dd1c4c716da
- 피트니스 패스 구매 페이지 API 구현

✨ [Feat] 피트니스 패스 구매 페이지 API 구현

---

src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java

Close #103 
- 구독 중 필드 값 수정
b69f79631dc9f5ffa87eb3513d31b8a0cb51fec8
- 구독 중 필드 값 수정

🐛 [Fix] 구독 중 필드 값 수정

---

src/main/java/com/example/fitpassserver/admin/dashboard/controller/DashboardAdminController.java
src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminService.java
src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminServiceImpl.java
src/main/java/com/example/fitpassserver/admin/fitness/controller/FitnessAdminController.java
src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminService.java
src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
src/main/java/com/example/fitpassserver/admin/member/controller/MemberAdminController.java
src/main/java/com/example/fitpassserver/admin/member/service/MemberAdminService.java
src/main/java/com/example/fitpassserver/admin/member/service/MemberAdminServiceImpl.java
src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminService.java
src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminServiceImpl.java
src/main/java/com/example/fitpassserver/admin/payment/controller/PaymentAdminController.java
src/main/java/com/example/fitpassserver/admin/payment/service/PaymentAdminService.java
src/main/java/com/example/fitpassserver/admin/payment/service/PaymentAdminServiceImpl.java
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

Close #101 
- 어드민 기본 설정
0465e6112a4f7c9d03b25de72c28b879adbde3e9

✨ [Feat] 어드민 기본 설정

---

src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java

Close #108 
- 보유 패스 조회 시설 정보 추가
92fb8df042d0a6e71fe7dd922932d9176c2a4964

♻️ refactor(memberfitness) 보유 패스 조회 시설 정보 추가

---

src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessImageService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessListService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessRecommendService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessSearchService.java
src/main/java/com/example/fitpassserver/domain/notice/controller/response/NoticeDetailResponse.java
src/main/java/com/example/fitpassserver/domain/notice/exception/NoticeErrorCode.java
src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java

Close #
- fitness, notice 이미지 받아오는 부분 : 각각의 테이블에 있는 image 컬럼에 있는 키 값으로 image 조회할 수 있도록 수정
f9ef32488fa52907ed51695e385f0519cc054b1a
image 컬럼에 있는 키 값으로 image 조회할 수 있도록 수정하였습니다.

:recycle: [refactor]: fitness, notice 이미지 받아오는 부분 수정

---

src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

:sparkles: [Feat] allow url 추가

---

src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java

Close #113 
- 피트니스 구매 조건 수정
07404e867eedc8e4260dc235d26ed684468b6a8d
- 피트니스 구매 조건 수정

🐛 [Fix] 피트니스 구매 조건 수정

---

src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java

Close #69 
- 보유 패스 조회 시설 사진 추가
47daffdb78c10fb61945f586baa5d8b3a0175f92

♻️ refactor(memberfitness) 보유 패스 조회 시설 사진 추가

---

src/main/java/com/example/fitpassserver/domain/notice/controller/response/NoticeListResponse.java
src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
src/main/java/com/example/fitpassserver/domain/notice/entity/NoticeType.java
src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java

Close #
- 공지사항 부분 공지인지 이벤트인지 type 추가
657c45eca851aa5a5249a0f8bfd917655acd1645
공지사항 부분 공지인지 이벤트인지 type 추가
공지 : ANNOUNCEMENT
이벤트 : EVENT

:recycle: [refactor]: 공지사항 부분 type 추가

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/CoinSinglePayRequestDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PlanSubScriptionRequestDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java

:recycle: [Refactor]: 카카오페이 구매 백엔드 요청으로 변경

---

src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessPaymentResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessRecommendResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessRecommendService.java

♻️ refactor(memberfitness) dto 변수명 수정

---

src/main/java/com/example/fitpassserver/domain/notice/controller/response/NoticeDetailResponse.java
src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java

공지사항을 클릭할 때마다 조회수 +1 하도록 구현
Close #
- 공지사항을 클릭할 때마다 조회수 +1 하도록 구현
979fd264935bc71862bf886856de28ff71b9d11b
조회수 기능 추가 구현
views 컬럼 0 으로 초기화
조회요청 받을때마다 increaseViews() 호출 해서 +1 하고 저장

:recycle: [refactor] : 조회수 기능 추가

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java

:recycle: [Refactor]: 플랜 api url 변경

---

src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
src/main/java/com/example/fitpassserver/domain/plan/repository/PlanRepository.java

:bug: [Fix]: 코인 구매 내역 패스 구독 여부 수정

---

src/main/java/com/example/fitpassserver/domain/coin/entity/CoinType.java
src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/CoinPaymentHistoryResponseListDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/entity/CoinPaymentHistory.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/repository/CoinPaymentRepository.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
src/main/java/com/example/fitpassserver/domain/plan/exception/PlanErrorCode.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanScheduler.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java

Close https://github.com/UMC-7-FIT-PASS/Fitpass-server/issues/123
-

:recycle: [Refactor]: 코인 구매 내역 갯수 컬럼 추가 및 에러 처리 추가

---

src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/Status.java
src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java

Close #128
- 패스 상태 추가
- 그에 따른 로직 변경
73d9cf04d6ef2938da34cc4a2df2990a9384ff79

♻️ [Refactor] 패스 상태 추가

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
src/main/java/com/example/fitpassserver/domain/member/sms/util/SmsCertificationUtil.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
src/main/java/com/example/fitpassserver/domain/plan/dto/request/PlanChangeRequestDTO.java
src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
src/main/java/com/example/fitpassserver/domain/plan/exception/PlanErrorCode.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java

Close https://github.com/UMC-7-FIT-PASS/Fitpass-server/issues/124
- 요금제 변경 시 문자 발송
- 요금제 변경

✨ [Feat]: 정기결제 요금제 변경 로직 추가

---

src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java

Close #136 
- 대시보드 구매 조건 수정
9332c57a396e99e7c3ea36aefd767d1d8d3f7330
- 대시보드 구매 조건 수정

🐛 [Bug] 대시보드 구매 조건 수정

---

src/main/java/com/example/fitpassserver/admin/dashboard/controller/DashboardAdminController.java
src/main/java/com/example/fitpassserver/admin/dashboard/converter/DashBoardConverter.java
src/main/java/com/example/fitpassserver/admin/dashboard/dto/response/DashBoardResponseDTO.java
src/main/java/com/example/fitpassserver/admin/dashboard/entity/DashBoard.java
src/main/java/com/example/fitpassserver/admin/dashboard/repository/DashBoardRepository.java
src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminService.java
src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminServiceImpl.java
src/main/java/com/example/fitpassserver/admin/dashboard/util/VisitorUtil.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/member/repository/MemberRepository.java
src/main/java/com/example/fitpassserver/global/config/WebConfig.java
src/main/java/com/example/fitpassserver/global/config/interceptor/VisitorInterceptor.java

Close #97 
- Admin 대시보드 구현
c7b559ab52fba517fe64b0f7ed5c71cd9db2fdbf
337981ce59c74201b59be0a737f7359c88f79d2e
- Admin 대시보드 구현

✨ [Feat] Admin 대시보드 구현 (페이지 뷰 제외)

---

src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java

Close #142
- 컨버터 메서드에 service 매개변수 제거
2582a019562ca6f6f2dbb72674262cfed7b1b88c

♻️ refactor(pass) 패스 시설 조회 로직 수정

---

src/main/java/com/example/fitpassserver/admin/payment/controller/PaymentHistoryAdminController.java
src/main/java/com/example/fitpassserver/admin/payment/converter/PaymentHistoryAdminConverter.java
src/main/java/com/example/fitpassserver/admin/payment/dto/response/CoinPaymentHistoryResponseDTO.java
src/main/java/com/example/fitpassserver/admin/payment/dto/response/PassPaymentHistoryResponseDTO.java
src/main/java/com/example/fitpassserver/admin/payment/exception/PaymentHistoryAdminErrorCode.java
src/main/java/com/example/fitpassserver/admin/payment/exception/PaymentHistoryAdminException.java
src/main/java/com/example/fitpassserver/admin/payment/service/PaymentAdminService.java
src/main/java/com/example/fitpassserver/admin/payment/service/PaymentAdminServiceImpl.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/repository/CoinPaymentRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/Status.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/member/repository/MemberRepository.java
src/main/java/com/example/fitpassserver/global/apiPayload/ApiResponse.java

Close https://github.com/UMC-7-FIT-PASS/Fitpass-server/issues/140
-

✨ feat: 어드민 구매내역 구현 

---

src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberResponseDTO.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/member/sms/controller/SmsController.java
src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java

Close #150 
- 로그인시 role 반환 및 컨트롤러 tag 추가

:recycle: [Refactor] 로그인시 role 반환 및 컨트롤러 tag 추가

---

src/main/java/com/example/fitpassserver/domain/fitness/exception/MemberFitnessErrorCode.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessCustomRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessCustomRepositoryImpl.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/fitness/util/PassStatusScheduler.java

Close #148 
- 패스 구매 조건 및 패스 상태 변경 로직 수정
b9815fbf78617f64cb8b5c5b1e351332b4442828
- 패스 상태 변경 로직 수정
5598b456208034b1931c673134f70465eb38f042
- 패스 구매 조건 수정 및 24시간 뒤 자동 구매 취소 로직 구현

🐛 [Fix] 패스 구매 조건 및 패스 상태 변경 로직 수정

---

src/main/java/com/example/fitpassserver/admin/dashboard/controller/PageViewController.java
src/main/java/com/example/fitpassserver/admin/dashboard/converter/PageViewConverter.java
src/main/java/com/example/fitpassserver/admin/dashboard/dto/response/PageViewResponseDTO.java
src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminServiceImpl.java
src/main/java/com/example/fitpassserver/admin/dashboard/util/VisitorUtil.java
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

Close #152 
- 페이지 뷰 기능 구현
f710d75f1fcb695516ff2dc0617bd41f1b4610ec
- 페이지 뷰 기능 구현

✨ [Feat] 페이지 뷰 기능 구현

---

src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/entity/CoinPaymentHistory.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/exception/KakaoPayErrorCode.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
src/main/java/com/example/fitpassserver/domain/plan/exception/PlanErrorCode.java
src/main/java/com/example/fitpassserver/domain/plan/repository/PlanRepository.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanScheduler.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java

♻️ [Refactor] 구매내역 및 카카오페이 결제 로직 리팩토링 

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/exception/KakaoPayErrorCode.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryRedisService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanRedisService.java

♻️  [Refactor] 코인, 플랜 구매 버그 수정 및 redis 추가

---

src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
src/main/java/com/example/fitpassserver/admin/notice/dto/response/AdminNoticeDetailDTO.java
src/main/java/com/example/fitpassserver/admin/notice/dto/response/NoticeDraftResDTO.java
src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminService.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java

Close #
- get api 추가
99e0c517888f59da3538ea2601ef8ae49cf93c52
아이디도 반환하도록 수정
상세조회 api 추가

:recycle:  [Refactor] 어드민 공지사항 수정

---

src/main/java/com/example/fitpassserver/domain/member/entity/Member.java

Close #158
- 사용자 생성 시 위도 경도 기본값 설정
2475c55e36cadaf965163eeef6bafaf996c65359

♻️ [Refactor] 사용자 생성 시 위도 경도 기본값 설정

---

src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
src/main/java/com/example/fitpassserver/admin/fitness/dto/request/FitnessAdminRequestDTO.java
src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java

Close #162
- 피트니스 time 저장&응답 수정
6f829399db19d80d8040af678e1a667f40459926

♻️ refactor(fitness) 피트니스 time 저장&응답 수정

---

src/main/java/com/example/fitpassserver/admin/management/controller/ManagementAdminController.java
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

:recycle: [Refactor] 구독/코인 요금제 조회 url 변경

---

src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessPaymentResponse.java
src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java

Close #172
- 피트니스 구매 화면 수정
edb15c389c4459643f90e7970760034b6e900a99

♻️ refactor(fitness) 피트니스 구매 화면 수정

---

src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java

Close #175 
- 패스 구매 조건 수정
e217f322986c335c816ba6a0c8407238fe804490
- 패스 구매 조건 수정

🐛 [Fix] 패스 구매 조건 수정

---

src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
src/main/java/com/example/fitpassserver/domain/member/sms/util/SmsCertificationUtil.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
src/main/java/com/example/fitpassserver/domain/plan/dto/event/PlanCancelSuccessEvent.java
src/main/java/com/example/fitpassserver/domain/plan/dto/event/PlanCancelUpdateEvent.java
src/main/java/com/example/fitpassserver/domain/plan/dto/event/PlanChangeAllSuccessEvent.java
src/main/java/com/example/fitpassserver/domain/plan/dto/event/PlanChangeSuccessEvent.java
src/main/java/com/example/fitpassserver/domain/plan/dto/response/ChangePlanDTO.java
src/main/java/com/example/fitpassserver/domain/plan/dto/response/KakaoCancelResponseDTO.java
src/main/java/com/example/fitpassserver/domain/plan/dto/response/SIDCheckResponseDTO.java
src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
src/main/java/com/example/fitpassserver/domain/plan/exception/PlanErrorCode.java
src/main/java/com/example/fitpassserver/domain/plan/listener/PlanSubscriptionEventListener.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java

Close https://github.com/UMC-7-FIT-PASS/Fitpass-server/issues/174
-

🐛 [Fix] 카카오페이 정기결제 확인 에러처리 및 리팩토링

---

src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java
src/main/java/com/example/fitpassserver/global/aws/s3/service/S3Service.java

:recycle: [Refactor] 프로필 이미지 변경 presigned url 로직 추가

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
src/main/java/com/example/fitpassserver/domain/plan/converter/PlanConverter.java
src/main/java/com/example/fitpassserver/domain/plan/dto/response/PlanStatusResponseDTO.java

Close #
- 정기결제 상태확인 response 변경

:recycle: [Refactor] 정기결제 상태확인 response 변경

---

src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java

🐛 [Fix] 패스 구매 제한 임시 해제

---

src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberResponseDTO.java
src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java

Close #193 
- 회원가입시 위치정보 동의 반환

:recycle: [Refactor] 회원가입시 위치정보 동의 반환

---

build.gradle
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java

Close #195 
- 회원테스트위한 중복 전화번호 임시 허용

🐛 [Fix] 중복 전화번호 임시 허용

---

src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberResponseDTO.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java

Close #196 
- 로그인, 회원가입시 위치정보 반환

:bug: [Fix} 로그인, 회원가입시 위치정보 반환

---

src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
src/main/java/com/example/fitpassserver/admin/notice/exception/NoticeAdminErrorCode.java
src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminService.java
src/main/java/com/example/fitpassserver/domain/member/entity/Role.java
src/main/java/com/example/fitpassserver/domain/notice/controller/NoticeController.java
src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
src/main/java/com/example/fitpassserver/domain/notice/exception/NoticeErrorCode.java
src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
src/main/java/com/example/fitpassserver/owner/notice/controller/NoticeOwnerController.java
src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerService.java
src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerServiceImpl.java

Close #202
- 공지사항 사장님 체크 박스 추가로 인한 로직 변경(등록, 조회)
- 사용자 권한 추가
b5ce770e0d2902f31b70c809e7e723483e6621f8
- 공지사항 엔티티 필드 추가
17ec2bc53c0b3348a322d7b8708fccfcfd43a4ea
- 공지사항 등록 로직 수정
9889b710d3d1c891aa4d6f3c2f1636b45fdb5c4b
- 공지사항 조회 로직 수정
8c0ce9e3ad36ab059276a3ba2ee2f94b79a0a72e

♻️ [Refactor] 공지사항 사장님 로직 

---

src/main/java/com/example/fitpassserver/admin/fitness/controller/FitnessAdminController.java
src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
src/main/java/com/example/fitpassserver/admin/fitness/dto/request/FitnessAdminRequestDTO.java
src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminService.java
src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java

Close #204
- 시설 수정, 삭제 및 구매상태 변경 API 구현
- 시설 수정 API 구현
0bb862706ab31e9adef55b639e9ccd76031cca84
- 시설 삭제 API 구현
046205450789f2f285a838841dfce1dd27edff55
- 구매상태 변경 API 구현
7ff6585e567f7fc7a8d58804c2daf603708258a0

✨ [Feature] 시설 UD 구현

---

src/main/java/com/example/fitpassserver/admin/notice/converter/NoticeAdminConverter.java
src/main/java/com/example/fitpassserver/admin/notice/dto/response/NoticeAdminResDTO.java

Close #207
- 어드민 응답 시 사용자 표시 체크박스 응답 추가
ec86e08c9c591fa29e28460d289e4d24e4fbb44b

🐛 [Fix] notice 어드민 응답 수정

---

src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java

🐛 [Bug] 코인 개수 오류 수정

---

src/main/java/com/example/fitpassserver/domain/notice/controller/NoticeController.java
src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java

Close #213
- 홈 슬라이드 공지 조회 인가 해제
c1369050e9374823e6e3e232c920b9cc565d7535

🐛[Fix]: 홈슬라이드 공지 이미지 조회 API 수정

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java

Close #209 
- CoinPaymentHistory 코인 개수 수정
https://github.com/UMC-7-FIT-PASS/Fitpass-server/commit/434eb2d35d5df4df62429658a786877e8333f817
- CoinPaymentHistory 코인 개수 수정

🐛 [Fix] CoinPaymentHistory 코인 개수 수정

---

src/main/java/com/example/fitpassserver/domain/coin/repository/CoinTypeRepository.java
src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/controller/FitnessHistoryController.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/converter/FitnessHistoryConverter.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/dto/RevenueHistoryResponseDTO.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/dto/UsageHistoryResponseDTO.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/service/FitnessHistoryService.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/service/FitnessHistoryServiceImpl.java

Close #212
-  정산내역, 업체 당 사용자 이용내역 로직 구현

:sparkles: [feat]: 업체 정산내역, 업체 당 사용자 이용내역 로직 구현

---

src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/converter/FitnessHistoryConverter.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/dto/UsageHistoryResponseDTO.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/service/FitnessHistoryServiceImpl.java

Close #220 
- 업체 사용자 이용내역에 사용한 코인만 표기한다.

♻️ [Refactor]: 업체 사용자 이용내역에 사용한 코인 표기 수정 

---

src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java

Close #224 
- 일반 유저 회원가입시 설문 추가 및 위치 동의 업데이트

:recycle: [Refactor] 일반 유저 회원가입시 설문 추가

---

src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PGRequestDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PortOneRequestDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/PGResponseDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/PortOneResponseDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/exception/PortOneErrorCode.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/exception/PortOneException.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/listener/CoinPaymentEventListener.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/query/PGPaymentQueryService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/query/PGPaymentQueryServiceImpl.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOneApiUtil.java

Close #216 
- PG사 API 연결 정기 결제 제외
https://github.com/UMC-7-FIT-PASS/Fitpass-server/commit/d917a3360a00f3146da2e548b7580ac0c90b1116
- PG사 API 연결 정기 결제 제외

✨ [Feat] PG사 API 연결 정기 결제 제외

---

src/main/java/com/example/fitpassserver/owner/dashboard/controller/DashboardOwnerController.java
src/main/java/com/example/fitpassserver/owner/dashboard/service/DashboardOwnerService.java
src/main/java/com/example/fitpassserver/owner/dashboard/service/DashboardOwnerServiceImpl.java
src/main/java/com/example/fitpassserver/owner/notice/controller/NoticeOwnerController.java
src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerService.java
src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerServiceImpl.java
src/main/java/com/example/fitpassserver/owner/owner/controller/OwnerController.java

🐛  [Fix] @CurrentOwner로 변경

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/listener/CoinPaymentEventListener.java
src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/kakaoNotice/template/AlimtalkTemplate.java
src/main/java/com/example/fitpassserver/domain/kakaoNotice/util/KakaoAlimtalkUtil.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/plan/dto/event/PlanChangeAllSuccessEvent.java
src/main/java/com/example/fitpassserver/domain/plan/listener/PlanSubscriptionEventListener.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanScheduler.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java
src/main/java/com/example/fitpassserver/domain/review/entity/ReviewNotification.java
src/main/java/com/example/fitpassserver/domain/review/repsotiory/ReviewNotificationRepository.java
src/main/java/com/example/fitpassserver/domain/review/scheduler/ReviewNotificationScheduler.java
src/main/java/com/example/fitpassserver/domain/review/service/ReviewReminderService.java
src/main/java/com/example/fitpassserver/global/config/RestTemplateConfig.java

Close #233
- 알림톡 구현
- 패스 사용 후 리뷰 알림 스케쥴러 적용
- 알림톡 enum 추가
de9d1855e862424d8f5e5f14729c6f0f57899bfe
- RestTemplate 빈 등록 
11c14505e74518439f8263d66184688be4e7b5df
- 리뷰 후기 알림 저장용 엔티티 추가
e778858be0184227bb4157751f0183f461e8491d
- 리뷰 후기 알림 스케쥴러
46c687b83f7054c6551d5421d7e4ad435eeb8aa0
- 기존 코드에 알림톡 메서드 교체
5c45aee9e9c9519118651c7d8f3e420e793ece69

♻️ [Refactor] 알림톡 구현

---

src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PGRequestDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/PGResponseDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOneApiUtil.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOnePaymentIdUtil.java
src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
src/main/java/com/example/fitpassserver/domain/plan/entity/PaymentType.java
src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
src/main/java/com/example/fitpassserver/domain/plan/listener/PlanSubscriptionEventListener.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanScheduler.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java

Close #230 
- PG사 정기결제 API 구현
https://github.com/UMC-7-FIT-PASS/Fitpass-server/commit/db5eb0a37e0ac53a048c4de3f7ef472b5d88eea5
- PG사 정기결제 API 구현

✨ [Feat] PG사 정기결제 API 구현

---

src/main/java/com/example/fitpassserver/global/common/dto/CommonResponseDTO.java
src/main/java/com/example/fitpassserver/global/common/service/CommonServiceImpl.java

:refactor: [Refactor] login 시 응답에 유저 아이디 추가

---

src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java

Close #230 
- 카드 목록 가져오기 Http method 변경
https://github.com/UMC-7-FIT-PASS/Fitpass-server/commit/1b284869a63ab151daf997bf91d1a51965dd96e6
- 카드 목록 가져오기 Http method 변경

🐛 [Fix] 카드 목록 가져오기 Http method 변경

---

src/main/java/com/example/fitpassserver/global/common/dto/CommonResponseDTO.java
src/main/java/com/example/fitpassserver/global/common/service/CommonServiceImpl.java

Close #
-  login 시 응답에 멤버 아이디, 이름 추가

:refactor: [Refactor] login 시 응답에 멤버 아이디, 이름 추가

---

src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java

♻️  [Refactor] 위치동의 팝업 api 수정

---

src/main/java/com/example/fitpassserver/global/common/service/CommonServiceImpl.java

Close #243 
- 사장님 로그인시 로그인시 ownerId, ownerName 반환
183c07488fc2a0a95fada9ebd1fae6930c92a31e

:recycle: [Refactor[ 로그인시 ownerId, ownerName 반환

---

.github/workflows/deploy.yml
build.gradle
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java

♻️ [Refactor] 무중단 배포

---

.github/workflows/deploy.yml

♻️ [Refactor] 로컬 Nginx 사용

---

src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
src/main/java/com/example/fitpassserver/admin/notice/converter/NoticeAdminConverter.java
src/main/java/com/example/fitpassserver/admin/notice/dto/request/NoticeAdminReqDTO.java
src/main/java/com/example/fitpassserver/admin/notice/dto/response/NoticeAdminResDTO.java
src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminServiceImpl.java
src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerServiceImpl.java

Close #249
- 공지사항 등록 시 체크박스 필드 추가 
30f064ec0b08eff07b60c47566b1a07dd701719c
- 사업자 공지사항 조회 수정
d4e01e0e6fe00516b0924cf78e18d0f3bf44a8c1
- 공지 페이지네이션 값 통일
a0891329040bd95b6545ce03ab5c557bc73bf486
- 공지사항 등록 시 체크박스 필드 추가 
- 사업자 체크박스 로직 추가
- 사업자 공지사항 조회 수정

♻️ [Refactor] 공지사항 리팩토링

---

src/main/java/com/example/fitpassserver/admin/owner/controller/OwnerAdminController.java
src/main/java/com/example/fitpassserver/admin/owner/converter/OwnerAdminConverter.java
src/main/java/com/example/fitpassserver/admin/owner/dto/OwnerAdminResponseDTO.java
src/main/java/com/example/fitpassserver/admin/owner/service/command/OwnerAdminCommandService.java
src/main/java/com/example/fitpassserver/admin/owner/service/command/OwnerAdminCommandServiceImpl.java
src/main/java/com/example/fitpassserver/admin/owner/service/query/OwnerAdminQueryService.java
src/main/java/com/example/fitpassserver/admin/owner/service/query/OwnerAdminQueryServiceImpl.java
src/main/java/com/example/fitpassserver/owner/owner/entity/Owner.java
src/main/java/com/example/fitpassserver/owner/owner/entity/OwnerStatus.java
src/main/java/com/example/fitpassserver/owner/owner/repository/OwnerRepository.java

Close #251 
- 시설회원 어드민 기능 추가 
- 시설회원 상태 추가
90ec5bc5b99e53518876fa825de428f95c9e15ac
- 시설회원 정보 api 
6e3a21c2e386c2d2f6d170680a67702f1194a383
- 시설회원 승인 api
d8ca6c2b0bddbe0e05c22e6f003c1a2b662c80e4
- 시설회원 승인/반려 api
5247ccbad211a10b5574867c047c33ea0a40541e
- 시설회원 파일 조회 api 
33323fc49d89d5a1a35e3f71d3bbbbcb348c6183

✨ [Feature] 시설회원 어드민 기능 추가 

---

src/main/java/com/example/fitpassserver/domain/kakaoNotice/template/AlimtalkTemplate.java
src/main/java/com/example/fitpassserver/domain/kakaoNotice/util/KakaoAlimtalkUtil.java
src/main/java/com/example/fitpassserver/domain/member/sms/service/SmsServiceImpl.java

Close #255 
-  회원가입 인증코드 카톡 발송으로 변경

:recycle: [Refactor] 회원가입 인증코드 카톡 발송으로 변경

---

src/main/java/com/example/fitpassserver/admin/member/controller/MemberAdminController.java
src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
src/main/java/com/example/fitpassserver/global/config/SwaggerConfig.java
src/main/java/com/example/fitpassserver/owner/fitnessHistory/controller/FitnessHistoryController.java
src/main/java/com/example/fitpassserver/owner/owner/controller/OwnerController.java

:rocket: [Chore] Swagger 회원별 정리

---

src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
src/main/java/com/example/fitpassserver/admin/notice/converter/NoticeAdminConverter.java
src/main/java/com/example/fitpassserver/admin/notice/dto/request/NoticeUpdateReqDTO.java
src/main/java/com/example/fitpassserver/admin/notice/dto/response/NoticeAdminResDTO.java
src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminServiceImpl.java
src/main/java/com/example/fitpassserver/domain/notice/controller/NoticeController.java
src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java

Close #261
- 공지사항 수정 API 추가
- 공지사항 체크박스 로직 수정
- 공지사항 권한 별 조회 로직 수정
4cf2e5eaf90ab1247f914456b11ce5a1d1b16e86

♻️ [Refactor]: 공지사항 로직 리팩토링

---

src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
src/main/java/com/example/fitpassserver/domain/plan/dto/event/RegularSubscriptionEvent.java
src/main/java/com/example/fitpassserver/domain/plan/dto/request/NotificationInfo.java
src/main/java/com/example/fitpassserver/domain/plan/entity/planLog/LogType.java
src/main/java/com/example/fitpassserver/domain/plan/listener/PlanSubscriptionEventListener.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanRedisService.java
src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java
src/main/java/com/example/fitpassserver/domain/plan/service/scheduler/PlanScheduler.java

Close #257
- 정기 결제 성공후 redis에 저장

♻️ [Refactor] 결제 성공 시에도 09시에 알림으로 변경

---

src/main/java/com/example/fitpassserver/admin/fitness/controller/FitnessAdminController.java
src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
src/main/java/com/example/fitpassserver/admin/fitness/dto/response/FitnessAdminResponseDTO.java
src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminService.java
src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java

Close #269
- 어드민 시설 단일 조회 API
f336b70fe76209fb2d6bace0ed4eb1b6d4a4fb9f

:sparkles: [Feat]: 어드민 시설 단일 조회 API

---

src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java

✨ [Feat] 리뷰 작성 시 코인 지급

---

.github/workflows/deploy.yml
.gitignore
build.gradle
src/main/java/com/example/fitpassserver/global/aws/s3/service/S3Service.java
src/main/java/com/example/fitpassserver/global/config/GoogleDriveConfig.java
src/main/java/com/example/fitpassserver/global/google/drive/exception/GoogleDriveErrorCode.java
src/main/java/com/example/fitpassserver/global/google/drive/exception/GoogleDriveException.java
src/main/java/com/example/fitpassserver/global/google/drive/service/GoogleDriveService.java
src/main/java/com/example/fitpassserver/owner/owner/service/command/OwnerCommandServiceImpl.java
src/main/java/com/example/fitpassserver/owner/owner/service/file/OwnerFileService.java
src/main/java/com/example/fitpassserver/owner/owner/service/file/OwnerFileServiceImpl.java

Close #264 
- 사업자 회원가입 시 구글 드라이브에 파일 저장

✨ [Feat] 사업자 회원가입 시 구글 드라이브에 파일 저장

---

build.gradle
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/CompletePaymentRequest.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PaymentCustomData.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PaymentDTO.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PaymentSession.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/StartPaymentRequest.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/PaymentIdResponse.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/NewCoinPaymentHistoryRedisService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandService.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandServiceImpl.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/query/PGPaymentQueryServiceImpl.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOneApiUtil.java
src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOneUtil.java
src/main/java/com/example/fitpassserver/global/config/PortOneConfig.java
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
src/main/resources/static/index.html

Close #274 
- 포트원 테스트 결제 로직 추가

 ✨ [Feat] 포트원 테스트 결제 로직 추가

---

src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
src/main/java/com/example/fitpassserver/global/oauth/OAuthAttributes.java

:bug: [Fix] 소셜 로그인 시 필드 변경

---

build.gradle
docker-compose.yml
prometheus.yml
src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
src/main/resources/logback.xml

Close #277 
- Prometheus, Grafana, Loki를 이용한 모니터링

:sparkles: Prometheus, Loki, Grafana를 이용한 모니터링

---

src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java

Close #286 
- 어드민 시설등록 리팩토링
* 6f1c89f0f3adca91d9e468bdec3193ad4865e77d

:recycle: [Refactor] 시설등록 owner 우선 매핑으로 변경

---

src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java

Close #288 
- 시설등록시 owner status 운영중으로 변경
* aab88a272d697ff19ceba9caa928eff3c1d0e7bb

:recycle: [Refactor] 시설등록시 owner status 운영중으로 변경
